### ISSUE TITLE
A stricter process for weekly sprints

### ISSUE THREAD

**Issue by venkatd** [coderly/process#18]
Let me start with the high level goals
- At the beginning of the sprint, we want to be confident that we can get everything done by the end of the sprint. We also want to be confident that we aren't handling more work than we should.
- Throughout the sprint, we want to make sure are on track. Are we still on track to finish everything? If not, what exactly is the reason? Is it that the task was harder than we expected? Was someone blocked? Were they not able to focus?

Keeping this in mind we can hone in on a solution.

Before we start working on a sprint, the following should be satisfied
- Each task is clear--as in a developer can get started building it
- Each task is assigned to someone
- Each task has a time estimate
- The total sprint time fits within the man hours we have allocated for the sprint

Once we start working on a sprint, the sprint should be locked down. This means that people can't just dump tasks into there without a process. New tasks need to go into a triage area. Tasks can't be scheduled into a sprint without first getting clarified.

Think of the sprint like this... If we have 3 developers for a 5 day sprint, that is 15 blocks of time. Each task/feature we work on takes up a certain block of time. Like a law of physics, we can't fit 18 blocks of time into a 15 block sprint. If they want to fit something in, something has to go. So one we fit the blocks in, we freeze the sprint and if they want to change it then they need to consider the blocks available and make the trade off with what has to go.

**Comment by joshsmith** [comment]
Agree with the high-level goals, it's the implementation details that I'm not sure about here.

What do know about points? Can we use points well here?

**Comment by venkatd** [comment]
I might have used different wording but I think it's the same. We can call it points since that's what other people seem to call it.

**Comment by joshsmith** [comment]
Points vs time estimation. It looks like most use a Fibonacci sequence. `1, 2, 3, 5, 8, 13`

**Comment by joshsmith** [comment]
This is going to be really hard the first couple weeks, but is supposed to get easier as you get more familiar with the sizing.

**Comment by joshsmith** [comment]
The point of the large step increases is to show how much larger something gets as you go up the scale.

**Comment by venkatd** [comment]
I don't see the benefit of points over saying, this task is a 2.5 day task. Am I missing something?

**Comment by venkatd** [comment]
It seems like an additional layer of abstraction that a client and we have to understand.

**Comment by joshsmith** [comment]
https://www.youtube.com/watch?v=90Xx8QVnXRc

**Comment by venkatd** [comment]
http://pm.stackexchange.com/questions/4251/why-would-teams-use-the-fibonnacci-sequence-for-story-points

> Some teams also use powers of two, or have a scale like 1, 2, 5, 8, 20. The idea is that the larger the story is, the more uncertainty there is around it and the less accurate the estimate will be. Using the Fibonacci sequence helps teams to recognise this uncertainty, deliberately creating a lack of precision instead of wasting time trying to produce estimates that might also carry a false degree of confidence.

**Comment by joshsmith** [comment]
Sprintly uses t-shirt sizes, which I think makes sense for backlogged stories, but not as much sense for a given week.

The point is that the next couple weeks are going to be really inaccurate, but the accuracy grows as we start to understand what our _velocity_ is, i.e. how many points we typically get done in a given week.

**Comment by venkatd** [comment]
I was thinking we can start simple by estimating days in half day increments and start adopting some of these practices as we feel the need to.

**Comment by venkatd** [comment]
Then if it's too simple we can keep these in the backlog to implement

**Comment by joshsmith** [comment]
I don't want to even start the habit of day estimation, even in blocks like that. If we're going to try to be agile, let's adopt the practices now and start out the first week or two by relating stories to hours ourselves internally, then throw of the hour estimation altogether.

**Comment by venkatd** [comment]
That's what we have been doing haven't we?

**Comment by venkatd** [comment]
I think the buckets thing makes sense:

> The fact that these 'buckets' are further apart imply that you are forced to make a choice between the less/more uncertain stories and choose which bucket is the most appropriate one.

**Comment by venkatd** [comment]
We could have our buckets be 0.5, 1, 2.5, and 5 days.

**Comment by joshsmith** [comment]
That's generally what we've been doing, but without assigning explicit point estimates to them.

I'm thinking something like a tag that's `1`, `21`, or having brackets in the task name like `[1] Task name`.

**Comment by venkatd** [comment]
I think decomposing time into points/velocity makes sense if we find that our estimates are way off. I like the brackets idea for putting the estimates there.

**Comment by joshsmith** [comment]
I'm saying for the purposes of us estimating these the first time around we can look at things in terms of the step increases of time and try to roughly estimate that way, but we present them as points.

We don't do this for every task we have, at least not the development ones. But for the `story` tasks, we do. Dev tasks simply support story tasks.

**Comment by joshsmith** [comment]
Time is used as the planning tool for the next couple weeks, but then we move over to points. It's going to be a rough transition, but I think one that's ultimately beneficial.

I think the `[XL] Task name` t-shirt sizing for backlogged tasks is additionally useful.

**Comment by venkatd** [comment]
What is the benefit to using a unit other than time?

**Comment by venkatd** [comment]
The benefit I see is that if our estimates are inaccurate then it will help us derive a more accurate estimate based on velocity, etc.

**Comment by venkatd** [comment]
Maybe we start with time for a few weeks and then discuss points? It'll be easier for me to wrap my head around the benefits once we start using days. I feel like these agile practices must have rose out of specific needs so might be better to take the same path and feel a little bit of pain.

**Comment by venkatd** [comment]
Nvm you just said that.

**Comment by joshsmith** [comment]
If you know velocity, you can derive the time. But if you set time, you have the potential for upsetting people by not getting as much done.

My suggestion is that we use time for now to estimate points. They're roughly the same.

Then when we have a sense for our velocity, we use points for our own planning.

**Comment by joshsmith** [comment]
If velocity changes it's not such a big deal, but if it looks like you're less productive – "You said this would take X hours and it took Y" – that becomes a more painful discussion.

The point of points is to make software development look from the outside as it actually works on the inside: estimates are rough and velocity will vary.

**Comment by venkatd** [comment]
Ok. I'm on board with that.

**Comment by joshsmith** [comment]
I think we've felt these pains before, so I'm guessing it will alleviate (though not eliminate) some of them.

I still really feel like it's going to be a painful process for a couple weeks, but a pain I'm willing to take on since it's better than the alternative right now, which is nothing.

**Comment by venkatd** [comment]
How do you feel about making sure we should follow pain-driven development to continue designing our process? We can see where we feel the pain, look outward for solutions to our pain, then test. That way we almost guarantee incorporating unnecessary process.

**Comment by joshsmith** [comment]
Agreed. For me, this suggestion (points) is pain-driven.

**Comment by joshsmith** [comment]
We're going to need to go back and refine with the new learnings and new pain we've felt here. I don't think "agile, because agile" is really what I'm suggesting here. Just that it's a sensible practice that seems to address a very real pain right now, especially when we're outlining a solution for what appears to be one of our most painful process breakdowns: sprint planning. Might as well stand on the shoulders of giants for the moment until we can figure out what does and does not work for us about it.

**Comment by venkatd** [comment]
What I mean is that someone else's process might not fit like a glove with Coderly. So for example, maybe there are aspects to a process that we need and parts that are just overhead. Imagine for example:
- We adopt days
- _We find the days is too inaccurate or clients are annoyed with our estimates_
- We incorporate points and velocity
- _We find that the granularity isn't good_
- We incorporate the fibonacci sequence or make larger buckets

So getting ourself to feel the pain of each aspect, even for a little while, is IMO a good safeguard against accidentally including steps we don't need. I could be wrong, but it feels harder to isolate and remove an unneeded process instead of not including in the first place.

Also, we will be intimately aware of the connection between the pain and the process we implemented. For example, we can say "Oh yeah points yeah we had to do that because we kept estimating 3 days and it never ended up being 3 days."

But imagine we adopt the fibonacci sequence right away without feeling the pain of doing it like 1, 2, 3, 4, 5. It feels to me like we would be using a solution that might do an OK job of solving our pain. (Or maybe it would do a great job but we don't know without feeling the pain.) We are skipping over the step of having and understanding that specific pain.

**Comment by venkatd** [comment]
> We're going to need to go back and refine with the new learnings and new pain we've felt here. I don't think "agile, because agile" is really what I'm suggesting here. Just that it's a sensible practice that seems to address a very real pain right now, especially when we're outlining a solution for what appears to be one of our most painful process breakdowns: sprint planning. Might as well stand on the shoulders of giants for the moment until we can figure out what does and does not work for us about it.

It's good to hear this from you. I agree about standing on the shoulders of giants. I think we're mostly on the same page. My main point is that I don't want to bring in a process all at once but would prefer doing it incrementally where possible.

**Comment by joshsmith** [comment]
I agree, I think this is what I was saying, just worded better.

Does doing time estimate => point estimate work okay for you? Or does that still not make sense?

Also, reason I wanted to adopt fibonacci right away was because I often have trouble communicating disparate size estimations between things.

I know you haven't needed to be present for many of the sprint planning conversations for basically the past year, so the pain is mostly mine. Just trying to figure out how to communicate why I think the things are solving pains that at least _I_ have had, and therefore we have had.

**Comment by venkatd** [comment]
This makes sense. It means we'd start to estimate what a point is worth over the next few weeks.

**Comment by joshsmith** [comment]
Yeah, so we present points right now externally, but don't use them internally for planning.

Right now:
- This task will take maybe 2 hours?
- Let's give it 2 points

In a week:
- How many points did we estimate?
- How many points did we finish?
- Were we over or under?

Soon:
- This task will take 2 points

**Comment by idelahoz** [comment]
I think a task shouldnt be more than a day. If its estimated to 2.5 for example thats a symptom that says that the task needs to be splited in smaller tasks. 

User stores estimated time should equal to the sum of the envolved tasks estimated time.

About hours vs points I've been in teams with both: measures and with points, people often end up asking "how much time will take you a 4 point task?" so a point end up being an hour or two, a 4 point task being a half day task ...., so I dont think there's a huge difference.

**Comment by joshsmith** [comment]
I don't think we should ever ask "how long would it take to do X # of points?" You can still set due dates for things, but that's not the same thing.

**Comment by venkatd** [comment]
So what you're suggesting is we start off with days but get them thinking in points so they understand that time estimates are hard. This way they don't get attached to a specific time estimate that we give them. Is that right?
