### ISSUE TITLE
If a task is labled as a question, should the PR also be labeled the same way?

### ISSUE THREAD

**Issue by begedin** [coderly/process#21]
## I have a task labeled as a question.

What do I do with the PR, if one exists? Is it also labeled as "question", or does it stay as whatever it is at the moment?

**Comment by venkatd** [comment]
@begedin could you create separate RFCs for each one? That way we can tackle these bit by bit as we get time.

**Comment by begedin** [comment]
@venkatd: Will do

**Comment by venkatd** [comment]
Are we talking about a GH task or an Asana task? Does #31 resolve this?

**Comment by begedin** [comment]
Asana task.

There's an Asana task which I labeled as a question and assigned to someone else (as per instructions). The instructions are unclear about what to do with the related PR in that case. Does it stay as is, or also gets labeled as a question?
