### ISSUE TITLE
Correct label for PR that isn't done nor blocked by a specific task, but advice is needed to proceed.

### ISSUE THREAD

**Issue by begedin** [coderly/process#24]
## I have a PR that isn't ready, I'm not blocked by any other task, but need advice on how to proceed.

This is a very specific scenario, an example is coderly/reissued-ember#309 

I started the work and got through (hopefully) most of it. I'm not sure how to proceed next, so I could use some advice. I'm also completely aware it isn't done yet. Do I mark it as "awaiting review", "needs work", both, or something else ("question") ?

**Comment by venkatd** [comment]
@begedin are you blocked in a situation like this?
Is #31 related to this? As in if resolve #31 will we resolve this?

**Comment by begedin** [comment]
Now that I think about it, and since we have #31, I'm thinking a combination of marking the PR blocked and creating issues for questions would deal with this specific case.

**Comment by joshsmith** [comment]
If we mark a PR as `blocked` and `question` both (https://github.com/coderly/process/issues/31#issuecomment-83054374), is it clear that this is blocked by a question?

**Comment by venkatd** [comment]
@JoshSmith I don't think the reviewer needs to know all the distinctions. His process should be to review everything and answer all questions.

The main consideration is the workflow and priorities of the reviewer. If he doesn't know what to do with a PR that has a certain label then that's an issue. If he has too many things that need his attention but not enough time that's an issue.

So I think the only questions that need to be answered are
- What do I need to do with this?
- What is its priority?

If he knows that then extra info is redundant. Also if he will know what he needs to do without a label then no need for a label IMO.
