### ISSUE TITLE
How do I label PRs that might end up not getting merged at all?

### ISSUE THREAD

**Issue by begedin** [coderly/process#25]
## I have a PR/code that might not get merged at all.

I started work on something, but it ended up being unnecessary, or the direction I took it in was wrong or there's some other reason why it likely won't get merged. What do I do with it?

Do I create a PR at all? Do I just drop the branch locally? What if the information in the PR is useful in some way? If I create a PR, how do I label it?

**Comment by venkatd** [comment]
Here you would just type a comment about why you are closing the PR and hit "close and comment". Could you create a PR for the documentation referencing this issue?

**Comment by begedin** [comment]
Made one #33
