### ISSUE TITLE
Testing checklist for each feature

### ISSUE THREAD

**Issue by venkatd** [coderly/process#27]
For each feature, I think we should have a human integration test. Here is what I mean. Let us say I worked on a feature and I got my PR merged. If I want someone else to test by hand that everything works as expected, what would my directions to them be?

So my proposal is this: _whenever you put something into awaiting review you must include a checklist in your PR of how they would need to test what you made by hand_

**Comment by venkatd** [comment]
Actually probably better when you start the PR. That way you have an idea of what the user-facing test is. This will force you to think about the user and how he will use the feature.

**Comment by joshsmith** [comment]
Yes, a thousand times yes.
