### ISSUE TITLE
Hotfix should get merged into master and development

### ISSUE THREAD

**Issue by venkatd** [coderly/process#29]
When we deployed today, we had some merge conflicts we had to resolve between development and master. The root cause of this issue was that hotfixes only get applied to master. If we apply a hotfix to both development and master we can avoid this issue.

Ideally we can have two PRs created when we type hotfix into the code tool.

**Comment by idelahoz** [comment]
https://github.com/coderly/code/pull/8

**Comment by venkatd** [comment]
@idelahoz Google for closing issues automatically with GitHub.
