### ISSUE TITLE
Rethink the purpose of our standups

### ISSUE THREAD

**Issue by venkatd** [coderly/process#3]
The guys at Zapier seem to do standups much differently than we do
https://zapier.com/blog/run-a-remote-meeting/
- People write up what they said they'd do and how it went in a blog post every week
- They don't talk about what they did and didn't do on the standup

We have different needs from them but it got me thinking. What is the purpose of our standup?
1. Staying in connected in a human way?
2. Making sure no one is blocked?
3. Peer pressure and keeping each other motivated?
4. Discussing issues?
5. Figuring out who works on what?

As you can see there are a lot of things we could be doing in the standup. Deciding on its purpose and the priority of each would help us design a better standup.

**Comment by joshsmith** [comment]
I think if we answer your questions in the context of "Do we want to do these?", the answers are:
1. Yes
2. Yes
3. Yes
4. Yes
5. Yes

But I'm not sure if we want to do all these on the standup or not.

I think there are at least two types of standups:
1. The kick-off standup, at the start of the week, to assign tasks, points, and get a feel for what we're committing to in a given week. This I think needs a certain amount of prep so this is not all done during standup time.
2. The daily standup. I think this is useful for giving people a voice that need it. I like the 5 minutes for questions, and if you have none, your time is done.

I want to remove as much dependency on the standup as possible, so starting there and extracting things out of it I think is the best path.
