### ISSUE TITLE
What to do when you have code related questions for a PR

### ISSUE THREAD

**Issue by venkatd** [coderly/process#31]
Sometimes when we are working on a feature we may have a handful of questions. When someone reviews a PR it is difficult for them to spot all the questions that need to be answered and some questions may go unanswered by accident.

What if we had a section called questions at the bottom of the PR? The owner of the PR is responsible for keeping that list up to date. If someone answers a question he can check the question off.

**Comment by begedin** [comment]
We're testing the approach of creating issues for each of the major questions.

Currently, I'm marking each issue with the "question" label, but the "RFC" label we have here might be more suitable. Should we add it to our reissued-\* projects, so we can use it for marking issues?

**Comment by venkatd** [comment]
We just experimented with creating separate question issues and referencing them in a PR. We found that this works pretty well. So the process would be:

For every question related to your task, create an issue with a the appropriate label and reference the original issue.

**Comment by venkatd** [comment]
Do you think we should still have a Questions section for each PR?

**Comment by venkatd** [comment]
What is the difference between an RFC and a question?

**Comment by begedin** [comment]
> Do you think we should still have a Questions section for each PR?

I'm not sure. If it's a bunch of minor questions, then it might be overkill to create separate issues, so a section might make sense.

> What is the difference between an RFC and a question?

Not much, but I'm thinking sometimes someone wants to go through all issues marked with a label by clicking on the label. If "question" is used both for PRs and issues, they might not get the list they were expecting.

**Comment by venkatd** [comment]
I think for the time being we should decide on a single label name. The label name is more important in terms of the action that needs to be taken. From what I see, in all of the cases, the person needs to respond in a comment so we can use RFC for everything.

If two labels require the same action I don't see a point in fragmenting the label. Better to have one label. Then the rule in our head is `if label = x, perform action y`.

**Comment by joshsmith** [comment]
Can we also add the `question` label to a PR?

**Comment by venkatd** [comment]
@JoshSmith what do you see as the benefit of doing that?

**Comment by joshsmith** [comment]
Makes it clear that there are unresolved questions from the outside. `blocked` is not enough.

**Comment by venkatd** [comment]
@JoshSmith I want to try and dig deeper with how the labels will be used. Is the reason that you want a distinction between `question` and `awaiting review` because of prioritization?

That's what I was thinking. I can quickly knock out the answers to questions throughout the day but I need a bigger block of time when reviewing PRs. So if we don't have the distinction then I can't prioritize.

I don't think it's a matter of knowing whether it is a question or not. That part should be obvious if they write their questions at the top of the PR.

Let us try and move the discussion to the workflow and how a label will support the workflow.
