### ISSUE TITLE
When should I deploy a hotfix?

### ISSUE THREAD

**Issue by idelahoz** [coderly/process#39]
Depending on the issue severity we should have a rule for when we should deploy the fix. for example:

 **dont allow abandoned orders to be submitted** https://github.com/coderly/reissued-api/pull/796  
This PR fixes a problem that happened on production with abandoned orders, this wont happen too often so I wasnt sure if deploying it right away was needed. And if not deploying right away, when should it be deployed? the next day at 6:00 PST?

There are also different kinds of issues with a different severity, so, how should we handle them?

**Comment by venkatd** [comment]
:+1: with describing with issue

I'm thinking we can deploy fixes each morning but 6 AM PST is a better time to deal with it since people aren't using the sight at that time.

@JoshSmith what do you think?

**Comment by idelahoz** [comment]
@venkatd yeah, I meant 06:00 PST, its 08:00 for me, so I wrote it wrong.

**Comment by idelahoz** [comment]
it also depends on the issue, and critical issue, needs to be deployed ASAP.

**Comment by venkatd** [comment]
I'm thinking that all hotfixes get deployed immediately.

**Comment by venkatd** [comment]
Is there a downside to this? To me it seems like a hotfix by definition is important so it should be deployed immediately.

**Comment by venkatd** [comment]
For now let us say every hotfix gets merged ASAP. @idelahoz make your titles more descriptive. I changed the issue name to "When should I deploy a hotfix?"

**Comment by idelahoz** [comment]
there may be fixes that are not "hot" then? I mean there are fixes that don't worth a downtime, should those cases go to the Feature normal process instead of the hotfix process?

**Comment by venkatd** [comment]
I think so. If we find a fix that doesn't belong in either one then let us create a task for that. Either way if we start doing more frequent deploys and feature flags then deploying the dev branch to production shouldn't be a problem.
