### ISSUE TITLE
Label process

### ISSUE THREAD

**Issue by joshsmith** [coderly/process#4]
Often labels get added in an incorrect order or left incomplete.

The general process should look something like:
- Task is created
- PR is opened
- PR is updated with link to relevant Asana tasks
- PR is given appropriate labels
- Asana tasks are updated with link to relevant PR
- Asana task is given labels that reflect PR
- When PR status changes, the PR labels are updated
- Immediately after, Asana labels are updated to reflect PR

**Comment by idelahoz** [comment]
How about task or PRs with multiple labels, like "needs work" and "awating review"? According to @venkatd's description of "awaiting review" that should not be possible.

**Comment by joshsmith** [comment]
@idelahoz I think this is a separate issue from the timing associated with labels. That's more "what do labels mean" IMO.

**Comment by joshsmith** [comment]
What's the status of this? Does everyone agree with my suggestion? Does this need a PR?

**Comment by venkatd** [comment]
Yeah this would need a PR and the above process would be split up to the right places. The simplest format for us to not lose track of is the when x then y format.

So like:

When you start a new feature on a task
- Type `code start name of the feature`
- Create a pull request
- ...
- etc

So all of our docs will be broken up into that format so whatever situation we're dealing with we can just jump to that section do execute the procedure.
