### ISSUE TITLE
Fix reviewed, needs work, and good after changes

### ISSUE THREAD

**Issue by venkatd** [coderly/process#40]
`needs work` seems to have taken on many meanings. By definition a PR that is not yet reviewed can be considered as needs work.

Because of this I think we should rename the label for their intended purposes is clearer.

What if we had the following labels
- reviewed but needs work
- reviewed and looks good

If we have a shorter name I'm open to ideas as well but I would prefer being explicit over confusing.

I think we can remove the good after changes label. It's to the judgement of the person working on the PR whether or not they need another review.

**Comment by joshsmith** [comment]
I'm not a huge fan of these names but I can't think of an alternative.
