### ISSUE TITLE
Doing now vs in progress

### ISSUE THREAD

**Issue by joshsmith** [coderly/process#43]
I'm not sure what the utility of `doing now` is: do I really care what someone is working on right this moment? I don't know.

That said, I think what we were attempting to convey with `doing now` before was simply that a PR was `in progress`.

I have to imagine that an `awaiting review` on an `in progress` PR is going to be much clearer than not.

**Comment by venkatd** [comment]
I feel that `in progress` is implied. Any PR in the list could be considered in progress? If there is no real meaning to `not in progress` then I don't see the need of `doing now` or `in progress`. I think our best bet is to leave out the label and if we feel pain from not having it, we add it in. 

Thoughts?

**Comment by begedin** [comment]
We could make use of a label that indicates, "out of all of my tasks, this is the one I'm currently working on", and "doing now" could be that label, if we decide to use it that way. I'm not sure we need something like that, though.

**Comment by venkatd** [comment]
The way I see it, if `doing now` is information that someone else can't act or make a decision on, then it might not be worth the overhead.

**Comment by joshsmith** [comment]
This is all fair enough.
