### ISSUE TITLE
Who is a question tag for?

### ISSUE THREAD

**Issue by joshsmith** [coderly/process#44]
I think the `question` tag lacks granularity. I'm never sure who a question is for. Is it for the submitter? From the submitter to the group?

In AMS we have `Needs Submitter Response` and `Needs Team Discussion` which makes it clearer what the actions are and when they're resolved. Although the submitter can't really change the tags, which is unfortunate.

Thoughts?

**Comment by venkatd** [comment]
I'm thinking we should decide how different cases should be handled, then work backwards from there to decide what the labels are. 

What should happen when someone has a question they need answer? Is it the same every time or are there different situations that get handled differently?

If they get handled differently, then how so?

**Comment by joshsmith** [comment]
It's not the same every time, because sometimes I have a question about a PR that needs an answer by the person working on it. Sometimes I have a question for others.

**Comment by venkatd** [comment]
Okay :+1: 

What should we call the person who created the PR? What do you think of owner?

**Comment by joshsmith** [comment]
I like submitter but not married either way.

**Comment by venkatd** [comment]
And as a general strategy I'd like to start the discussion as "what is the workflow?" or "what is the process we need to follow?" ... then the "what labels do we need?" will be obvious to us.

**Comment by venkatd** [comment]
I prefer owner because it gets us thinking of the ownership. You create a feature then you're the owner of that PR as in you're responsible for seeing it through.

Then in the documentation we can word things like "write the testing checklist for all of the PRs that you own" ... just a thought

**Comment by venkatd** [comment]
Then in the documentation we can word things like "write the testing checklist for all of the PRs that you own" ... just a thought

**Comment by joshsmith** [comment]
I think the question of the tags arose because it seemed obvious to me that questions come up from both directions. Given that, how do we clarify their salient differences?

**Comment by venkatd** [comment]
> And as a general strategy I'd like to start the discussion as "what is the workflow?" or "what is the process we need to follow?" ... then the "what labels do we need?" will be obvious to us.

Just was a reminder to help focus the conversation. Even if we were are already doing something, I find it helpful to spell things out.

**Comment by venkatd** [comment]
We could phrase things in the form like so
- As the owner of a PR I want to get a question answered about my PR 
- As the reviewer of a PR I have some questions about the PR I am reviewing

Suppose now the labels have been assigned.. what is the workflow of the person answering the question in each case?

**Comment by venkatd** [comment]
I was thinking if my workflow is
- Answer all questions that aren't mine
- Review all PRs awaiting review that aren't mine

(So I'd have a filter for "question" and "awaiting review")

Then we might not need a separate label. Thoughts?

**Comment by venkatd** [comment]
Either way I don't feel very strongly about this.

**Comment by venkatd** [comment]
I might be misunderstanding the motivation for this. What was the moment when you felt like the `question` label needed more context?

**Comment by joshsmith** [comment]
Here's an example where a `question` label needed more context: https://github.com/coderly/reissued-ember/issues/319#issuecomment-84069757

We've addressed the question now, but there's another question for the person who asked the original question. From the outside looking in, it's not obvious to @begedin that this was answered by anyone. Nor is it obvious to anyone else who's supposed to answer.

I just want to glance at the open PRs and know the state and what to do next. If, as the owner, I don't know if I need to respond, I may think this was my original question. And if I don't know as not-the-owner that someone has a question for me, it's hard to keep track.

There are so many sidebar conversations going that labels are really the only way to keep track from the outside.
