### ISSUE TITLE
Making it clear a task is a hotfix

### ISSUE THREAD

**Issue by joshsmith** [coderly/process#46]
I kept looking at a task for awhile this week that was a hotfix wondering: "why isn't this merged in yet?"

I also probably would have paid more attention to it if I knew it was a `hotfix`.

Can we find some way to make this clear?

**Comment by venkatd** [comment]
A hotfix label could be enough for this

**Comment by idelahoz** [comment]
@JoshSmith a hotfix label?

**Comment by joshsmith** [comment]
Haha I didn't phrase it that way because it's coming from a source of pain. But yes, I think a `hotfix` label is right.

**Comment by venkatd** [comment]
Yeah I like that you described the source of pain. I prefer starting the discussion around that.

**Comment by idelahoz** [comment]
@venkatd could the code gem add labels?, if its possible, we could add the label on the code publish for a hotfix.

**Comment by joshsmith** [comment]
@idelahoz open up a separate RFC for that and link here.

**Comment by idelahoz** [comment]
Issue for code gem https://github.com/coderly/process/issues/48
