### ISSUE TITLE
When a GitHub PR is merged, should tag Asana task as merged

### ISSUE THREAD

**Issue by joshsmith** [coderly/process#47]
Any time we merge a PR, it should be clear in Asana that the state of that PR has changed.

**Comment by idelahoz** [comment]
@JoshSmith so we dont check the task as done?

**Comment by joshsmith** [comment]
We can, but the idea is that the GH-Asana integration at least automatically marks the task as `merged`. Then we have insight into what the status is from Asana without having to jump into GH. And then it's still up to that person to mark as complete. But automating task completion is dangerous.
