### ISSUE TITLE
Revamping our Asana-GH process

### ISSUE THREAD

**Issue by venkatd** [coderly/process#5]
Right now when you look at a label, it is unclear what to do with that label. That is because some labels, such as `needs work` have many possible courses of action. There needs to be a 1-to-1 mapping between a label and what action you need to take with that label.

What we need to do is write out examples for every possible scenario and design our label system off of that. Essentially we need to think of all the [jobs](https://medium.com/@rjs/thinking-of-interfaces-as-sets-of-jobs-7d72f22948c3) we want to do because that's what really matters at the end of the day.

We need to see our process as a user interface. There are many things we are trying to accomplish. Let us write them all out. Then from those requirements we can design the best system.

Here is a list to get us started
- [ ] As a developer I need a review of my feature
- [ ] As a developer I want others to know that I am working on this feature
- [ ] As a developer I need to get some questions answered about the feature I am working on -- it's not urgent because I can keep working
- [ ] As a developer I need to get some questions answered about the feature I am working on -- it's urgent and I can't continue without getting my question answered
- [ ] As a PM I want to know what everyone is working on at any given point (maybe not necessary)
- [ ] As a PM I want to know if we are on track to complete the sprint on time
  - [ ] Related: As a PM I want to know if Joe Schmoe is on track to complete his tasks for the sprint
- [ ] As a developer/PM I need to know if anyone needs anything from me to complete their tasks

**Comment by venkatd** [comment]
For each "job" we want to accomplish to accomplish, we should ask the following questions:
- How are we currently doing for this? How well is it working?
- What are the problems with it? Any real world examples?
- What are the root cause of the problems?

We will also want to do a brain dump of all the problems we have encountered. Any time any of us have been annoyed or frustrated in the past few weeks, please write it as a comment below.

**Comment by joshsmith** [comment]
**As a developer I need a review of my feature**

Does this mean you need a review mid-feature or need a review because it's merge-able?

**Comment by joshsmith** [comment]
**As a developer I want others to know that I am working on this feature**

I would say that `doing now` is a good label here. That's exceptionally clear to my mind.

**Comment by joshsmith** [comment]
Can we create PRs per-task for these? I changed the list items above to checkboxes.

**Comment by joshsmith** [comment]
**As a developer I need to get some questions answered about the feature I am working on -- it's not urgent because I can keep working**

and

*\* As a developer I need to get some questions answered about the feature I am working on -- it's urgent and I can't continue without getting my question answered**

Maybe we modify the `question` tag to be `question` (grey) and `blocking question` (red)?

**Comment by joshsmith** [comment]
**As a PM I want to know what everyone is working on at any given point**

They don't seem to want this level of granularity, or it's not useful to them.

**Comment by joshsmith** [comment]
**As a PM I want to know if we are on track to complete the sprint on time**

I think this can be shown with stories (high-level business objectives) and due dates. If we're late on a story, then it should be obvious.

**Comment by joshsmith** [comment]
**As a developer/PM I need to know if anyone needs anything from me to complete their tasks**

What things might be needed besides a `question` and a `blocking question`?

**Comment by venkatd** [comment]
> As a developer/PM I need to know if anyone needs anything from me to complete their tasks
> 
> What things might be needed besides a question and a blocking question?

Maybe they need something from the client or they are waiting on one of on merging something. We might not need a lot of granularity on this though besides knowing that they need something. IMO the important part is what action is required for each label. _I'm looking at this label right now, how should I act on it?_

If the same action is required for a bunch of different labels, it may make sense just to have one label for it.

**Comment by joshsmith** [comment]
In this case, I think `blocked` is the label of choice. It's scary-sounding and attention-grabbing, especially when red.

**Comment by venkatd** [comment]
Agreed. I'm blocked--doesn't matter why--but I need X from Joe Schmoe so I can continue. I'll create separate RFCs for each scenario. Blocked is one of them.
