### ISSUE TITLE
How to handle not being able to put in full hours due to some reason?

### ISSUE THREAD

**Issue by begedin** [coderly/process#50]
To give an example, either on March 31st or April 1st, I'm getting a visit from my sister and her family. They'll be staying here for two weeks. I don't want to take full days off, but there is a good chance I won't be able to put in the full 8 hours each day because it's going to be way crowded, especially since they have a kid.

How to handle that?

I was thinking, we consider it as if I did take a few days off. Say, if I had to miss 16 hours total - that's 2 days off then.

I'm not really sure though.

I already mentioned this to @venkatd and we both agreed we should discuss this as a general issue, just so we have it clearly defined.

**Comment by venkatd** [comment]
Exchanging days off should generally be fine. Unless things get more complicated you could track it in a spreadsheet.

There may be times during a deadline period where we prefer for you make up the time instead but that can be dealt on a case-by-case basis unless it becomes more common.
