### ISSUE TITLE
When does a task get checked off?

### ISSUE THREAD

**Issue by joshsmith** [coderly/process#58]
The process right now indicates that something can have its label changed to `merged`. But when does the task get checked off? Who checks it off?

**Comment by begedin** [comment]
It might be useful to check them off at the end of a sprint. That way, we have an overview of what's done. Just an idea.

**Comment by venkatd** [comment]
Yeah I agree. When a task disappears for a sprint I think it's no good to hide it since it's out of sight and out of mind.

**Comment by joshsmith** [comment]
Just to play devil's advocate here, everything seems much more cluttered when completed tasks aren't marked as completed.

If we want an overview of what's done, you can look at the following:

![screen shot 2015-03-23 at 11 05 46 am](https://cloud.githubusercontent.com/assets/321667/6786954/9e38bc40-d14c-11e4-9d27-db9bfc18f4ba.png)

**Comment by venkatd** [comment]
What if it they were completed at the end of the day?

**Comment by joshsmith** [comment]
A task that's `merged` is no longer actionable except by marking it complete. I'm fine with user stories staying unchecked since that's a good high-level overview, but we're going to have a lot of detritus in there if we don't check off the broken down tasks.

**Comment by venkatd** [comment]
Ok I'm fine with it. Let us see if there's an issue with it and revisit if checking off becomes a problem.

**Comment by joshsmith** [comment]
Completed by whom at the end of whose day? If we're async and spread across timezones, that seems problematic.

**Comment by venkatd** [comment]
Nvm about that comment. I'm on board with just checking off right away.

**Comment by joshsmith** [comment]
I guess then the question is really: what benefit does the `merged` label have if we're checking it off immediately?
