### ISSUE TITLE
Write up "how to test" items at the start of the sprint

### ISSUE THREAD

**Issue by venkatd** [coderly/process#59]
If we have the "how to test" sections all written up on the first day we'll have a _much_ clearer idea of what goes in and does not go in the sprint.

We can write them into the Asana tasks.

**Comment by joshsmith** [comment]
Which tasks do they get written in? The stories? The dev tasks?

**Comment by venkatd** [comment]
Stories might make the most sense.

**Comment by venkatd** [comment]
Since the granularity of how to test is at the user level.

**Comment by idelahoz** [comment]
so the how to test would be a part of the original story description?

**Comment by joshsmith** [comment]
I think so.

**Comment by venkatd** [comment]
So we won't be having the how to test in the PRs anymore.

**Comment by joshsmith** [comment]
We shouldn't copy those over? I know it's extra overhead (in an overhead-ridden process). But I quite liked being able to quickly reference it in the PR.

**Comment by venkatd** [comment]
Yeah probably a good idea to copy from Asana => GH when you create the PR. It's good to have for reference in your PR during development anyway.

**Comment by joshsmith** [comment]
:+1:
