### ISSUE TITLE
Schedule for sprint planning

### ISSUE THREAD

**Issue by venkatd** [coderly/process#60]
When should a sprint get planned? Should we have the client give us the tasks for the upcoming sprint the week before? It seems kind of last minute to have to plan the sprint on the day the sprint gets kicked off.

Also I think we need a point where we get back to them and tell them if the sprint makes sense. When we are on the spot during a call we might end up agreeing to more than we can handle. When should this happen and how?

We should have a chance to go through this sprint to make sure everything makes sense.

**Comment by joshsmith** [comment]
Just commenting what some others do:

> So, ideally (and it's not always practical when you have multiple teams) I have sprint review on friday afternoon and planning on monday morning.
> http://pm.stackexchange.com/questions/3031/when-should-you-do-sprint-planning

**Comment by venkatd** [comment]
If we do planning on Monday we need an opportunity to get back to them with the finalized plan. We also need to account for potential back and forth when negotiating what goes in the sprint.

**Comment by joshsmith** [comment]
I think if we ask for the high-level to be given to us asynchronously by Thursday of the week before, we can spend some time on sprint planning Friday.

**Comment by joshsmith** [comment]
We might need to work backwards to this. When does development for the next week start? Early, early Monday morning US time because of @begedin.

**Comment by venkatd** [comment]
Yeah I like that. Then if we need them to get back to us, dig into feasibility, or there is some back and forth on what goes in the sprint, then we have a buffer for that.

I want to avoid not being able to kick things off on Monday. For example, it's unclear what @idelahoz and @begedin need to work on today.

**Comment by venkatd** [comment]
Yeah ideally we have the sprint mostly planned by EOD Friday. Monday is a matter of confirming that nothing has changed.

**Comment by venkatd** [comment]
Then also on our Monday meeting we can tell them what can and can't go in the sprint and make sure that things not in the sprint don't show up in the current sprint of Asana.

**Comment by idelahoz** [comment]
I think by the start of monday it should be mostly clear what the tasks should be, and now that we have @begedin on europe hour, this is even more critical.

**Comment by joshsmith** [comment]
And what does the sprint planning process itself look like? Do we break down stories and how do we compose them? How do we assign the broken down tasks? How do we estimate them?

I'd like it to be less management-driven and more developer-driven.
- We can all collectively say how long we think the high-level stories will take and average them out.
- Each of us takes ownership over a few of the stories.
- Each of us is responsible for breaking those stories down into tasks.
- If there are tasks that you can't do, assign them to someone else (maybe design, for example)
- ??? _Don't know if this makes sense_ Look at all the tasks you have and assign points to those individually

**Comment by joshsmith** [comment]
If we know how long this process typically takes, then we can determine the schedule. But I think it's hard to determine the schedule without knowing that.

**Comment by joshsmith** [comment]
I'd like to get the "how does sprint planning work?" discussion out of here and into that ^ issue instead.

**Comment by venkatd** [comment]
I think just as Monday is a special standup, Friday can also be a special one where we are focused on planning the upcoming sprint. Standup time is a time where we know we are all available.

**Comment by joshsmith** [comment]
Based on the async discussion happening in #62, I think this sprint planning has a window and a deadline, but not a specific synchronous time that it happens.

**Comment by venkatd** [comment]
Agree
