### ISSUE TITLE
How does sprint planning work?

### ISSUE THREAD

**Issue by joshsmith** [coderly/process#62]
We need to figure out how sprint planning works. Spawned by conversation in https://github.com/coderly/process/issues/60
- Do we break down stories and how do we compose them?
- How do we assign the broken down tasks?
- How do we estimate them?

I'd like it to be less management-driven and more developer-driven.
- We can all collectively say how long we think the high-level stories will take and average them out.
- Each of us takes ownership over a few of the stories.
- Each of us is responsible for breaking those stories down into tasks.
- If there are tasks that you can't do, assign them to someone else (maybe design, for example)
- ??? Don't know if this makes sense Look at all the tasks you have and assign points to those individually

**Comment by venkatd** [comment]
I'm guessing this would be a 1-2 hour process requiring all of us to be involved. But I think it can go like this:
- Ensure all high level stories are clarified
- Write more granular user stories aka acceptance criteria. These would look like client readable integration tests. For example:

```
- Consumer clicks on the search bar
- Consumer types in "pants"
- Consumer sees a gallery of all products with the keyword pants
```
- From these stories we create individual Asana tasks. It may not always be 1 story to 1 task. Sometimes it may be more than one story to a task.
- By this point it should be crystal clear what the outcomes for the end of the week are
- We assign points to the stories
- We assign stories to each of us

**Comment by joshsmith** [comment]
Is there no way we can do this asynchronously? It seems self-defeating to put all this effort into getting the rest of the process async and not have this be that way, too.

**Comment by venkatd** [comment]
Yeah I agree. Any suggestions on that?

**Comment by venkatd** [comment]
Okay first focus is getting user stories clarified. For example:

> Admin can run analytics on consumer search string archive

No description. That could mean anything.

So what do we need to do to get this clarified? Do we write down our interpretation and ask the if that's what they were asking for? Do we just tell them unclear and ask them to clarify with examples?

And of course how can we do this async?

**Comment by joshsmith** [comment]
Based on what you said, I'm envisioning a way that we can take the high-level stories and label them:
- `needs acceptance tests`
- We write those
- We use the acceptance tests to break down into more specific tasks like
  - Add analytics event for search to API

**Comment by joshsmith** [comment]
I think our job is to write down our interpretation and then clarify with them if needed.

**Comment by venkatd** [comment]
Okay. We could start with one acceptance test and ask them "Is this what you meant? Is there any functionality I am missing besides this?"

**Comment by venkatd** [comment]
Does this mean we'll need to assign stories before everything so everyone would be responsible for getting their stories clarified, writing acceptance tests, and creating dev tasks?

**Comment by joshsmith** [comment]
I think so, yes.

**Comment by joshsmith** [comment]
That said, I also think there's first-order clarification that should be done with us, before they need to clarify. We may be able to address some confusions before they need to.

**Comment by venkatd** [comment]
Okay I'm thinking you and I would be responsible for clarifying everything and all the acceptance tests. I'm thinking we should do it ourselves all to start with. Once we understand the process better we can start distributing the responsibility of that.

If there are ~~fridge~~ fringe cases that we haven't thought about, whoever is assigned the story can write additional acceptance tests and ask for further clarification.

**Comment by joshsmith** [comment]
What's a fridge case? :stuck_out_tongue_closed_eyes: 

I think you're right. For now, we handle this responsibility.

**Comment by venkatd** [comment]
> Fridge case: 1. A case to hold a refrigerator, generally made of wood.

So once we have written all the acceptance criteria, who assigns the points? Should we do that still?

Then at that point I think
- Whoever is assigned a story writes up the individual tasks for it
- They verify that the points make sense and that it is feasible to complete within the sprint
- If we aren't able to complete everything within a sprint we get back to them Friday EOD and provide them some options on what they can do.

**Comment by joshsmith** [comment]
I think we still assign points for now.
