### ISSUE TITLE
We could use a reliable way to tell/notify/find out when the next deployment is.

### ISSUE THREAD

**Issue by begedin** [coderly/process#71]
I had no idea there would be a deployment today. In fact, I got up and started work earlier to handle some stuff before the stand up, so I probably wouldn't be here during deployment if @JoshSmith didn't happen to be online and mention it to me.

I'm thinking we could use some sort of system so we can all reliably be aware when the next deployment is. Maybe slackbot could keep it in the reissued channel's title? If there's no room for that and the stand-up link at the same time, we could keep one in the general channel and the other in reissued.

**Comment by venkatd** [comment]
I vote for doing this:

https://zapier.com/zapbook/zaps/356/get-a-google-calendar-meeting-reminder-in-a-slack-channel-10-minutes-before-it-starts/

We can also make sure standups, etc, are in this calendar and slack can notify the whole channel in advance.
