### ISSUE TITLE
Feature flags

### ISSUE THREAD

**Issue by joshsmith** [coderly/process#74]
We need to add something regarding feature flags since we had a production push with functionality intentionally hidden behind a feature flag.

I'm not sure the best way to handle this other than as a manual process in a deploy to production.

**Comment by venkatd** [comment]
I think there are 2 solutions:
- We each go through the "things to test section" after deploy
- We insist that our clients test things shortly after deploy. They didn't become aware of this until 9pm... not sure what took them so long to test things out.

And potentially Rainforest QA might be a good thing to look into....
