### ISSUE TITLE
Unified inbox

### ISSUE THREAD

**Issue by venkatd** [coderly/process#8]
## The Problem

We got Asana comments to respond to, GitHub PRs to review, and questions to answer on GitHub. Because we have so many inboxes we end up missing things that we need to act on.
## The Solution

A unified inbox written in Ember. Because GH and Asana both have REST APIs, we could have a process as follows:
- Connect with Asana
- Select Asana projects
- Connect with GitHub
- Select GitHub Projects
- View a dashboard with all of the inbox items for all of the Asana and GitHub projects we got connected to
## Additional ideas
- We probably won't need a backend because if we write the proper Ember Data adapters, we could have a purely front end solution. And if we absolutely HAD to have a backend we could throw Firebase on there.
- We could make use of Chrome's desktop notifications feature. The app could poll all the projects every couple of minutes to check if there are any new items. We could set a badge in the title of the tab like "(5)".
- Mark something as read when you click on it
- Have slack bother us if we haven't checked our inbox in a while
- Set up rules to filter out inbox items that are relevant to us and important to us. For example, if we are explicitly mentioned.

**Comment by idelahoz** [comment]
If we want to bother us if we dont check the inbox for too long we would need a kind of backend.

It would be nice if the dashboard can relate github projects to asana projects to keep items organized, the next step would be tasks -> PRs.
